### PR TITLE
add ability to set metadata on PVCs nifikop creates

### LINKED ISSUE #267: No way to add annotation to PVC
There is no way to add an annotation to a PVC. Because of this, it is impossible to automatically tag AWS EBS after PVC creation, and there is no point in manually adding tags, since autoscaling works.
Please add this

### PR DESCRIPTION
**Pull request by mh013370**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #267 
| License         | Apache 2.0

### What's in this PR?

Adds the ability to attach labels and annotations to PVCs that nifikop creates.

### Why?

To attach additional context to the object.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [x] Append changelog with changes

### CODE REVIEW

**Review by Carverook — APPROVED** [review]

**Comment by mh013370** [comment]
@juldrixx : quick review?  🙂

**Comment by Carverook** [comment]
Hello, when can we expect a version with this fix? We really need a new version)

**Comment by mh013370** [comment]
@juldrixx : Thoughts on cutting a `v1.2.0` release?

**Comment by pranavarnav2** [comment]
@juldrixx we would love to get this feature as well, please do release a new version :)
Thanks!

**Pull request merged**
