### PR TITLE
Added nifi-cluster Helm chart

### LINKED ISSUE #102: Create helm chart for NifiCluster and referencing resources
## Feature Request

**Is your feature request related to a problem? Please describe.**

It'd be useful to model NiFi cluster deployments via a helm chart maintained alongside the operator.

**Describe the solution you'd like to see**

Self explanatory.

**Describe alternatives you've considered**

Maintaining a custom helm chart is not the greatest.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by mh013370**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #102 
| License         | Apache 2.0

### What's in this PR?

This PR contains a new helm chart called `nifi-cluster` which makes it possible to deploy all of the following in a single deployment:

- `NifiCluster`
- Zero or more `NifiUser`
- Zero or more `NifiDataflow`
- Zero or more `NifiRegistryClient`
- Zero or more `NifiParameterContext`
- Zero or more `NifiUserGroup`
- Zero or more `NifiNodeGroupAutoscaler`, including the associated `HorizontalPodAutoscaler`

It also allows for creating:

- An optional dependent zookeeper cluster specifically for this `NifiCluster` via the bitnami zookeeper chart
- [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) `ServiceMonitor` for metric scraping
- [BanzaiCloud Logging Operator](https://banzaicloud.com/docs/one-eye/logging-operator/) logging `Flow` for log aggregation
- Kubernetes `Ingress`
- Extra arbitrary manifests, which are useful to generate secrets containing sensitive properties referred to in `NifiParameterContext` resources

The nifikop and nifi-cluster charts will be versioned together to ensure that compatibility is clear.

### Why?

To ease the deployment of `NifiCluster` resources with all of the supporting custom resources.

### Additional context

We've been running this for some time and it works well for our needs.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [x] Append changelog with changes

### CODE REVIEW

**Comment by michael81877** [comment]
I will update this PR to specify API version `v1` now that nifikop 1.0.0 has been released.

**Comment by michael81877** [comment]
Alright i've updated this chart with all v1 resources (except the `v1alpha1.NodeGroupAutoscaler`). 

@erdrix : Would it be possible to pursue merging this so we can avoid maintaining this separately? Do you see any major issues with it?

**Comment by skpathak2** [comment]
Hello, I am trying to spin up a sidecar container using "sidecarConfigs" using nifi-cluster helm chart for nifikop however  I do not see a sidecar spinning up.

```
sidecarConfigs:
    - name: fetchflowfile
      image: "busybox"
      command: ["sh","-c","wget -P /opt/nifi/data https://storage.cloud.google.com/abc/flow.xml.gz"]
      volumeMounts:
        - name: logs
          mountPath: /opt/nifi/data
```

is it possible to share a working example ?

**Comment by mh013370** [comment]
@erdrix , @juldrixx : Any issue with getting this into `master`? It would drastically simplify NifiCluster deployments from many CRDs into a `helm install` command.

**Review by erdrix — APPROVED** [review]
Good for me, but if we want it to have a chance to be used, we might want to think about adding a documentation section in another PR :)

**Comment by mh013370** [comment]
> Good for me, but if we want it to have a chance to be used, we might want to think about adding a documentation section in another PR :)

I'm on it :)

Thanks!

**Pull request merged**
