### PR TITLE
Fixed grammar and confusing words.

### PR DESCRIPTION
**Pull request by aoinc13**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### Checklist

- [ ] Implementation tested
- [ ] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Review by mh013370 — APPROVED** [review]

**Review by mh013370 — CHANGES_REQUESTED** [review]
Can you please update the documentation in the non-versioned documentation here: 

https://github.com/konpyutaika/nifikop/blob/master/site/docs/3_manage_nifi/1_manage_clusters/1_deploy_cluster/4_ssl_configuration.md

This edit is only for the latest v1.10.0 release documentation.

**Comment by aoinc13** [comment]
I probably didn't do that correctly. It's in a new patch-2.

**Comment by aoinc13** [comment]
I committed the change this pull request and removed patch-2.

**Comment by mh013370** [comment]
> I committed the change this pull request and removed patch-2.

Thank you for your contribution!

**Review by mh013370 — APPROVED** [review]

**Pull request merged**
