### PR TITLE
Make NiFi pod readiness and liveness checks configurable

### LINKED ISSUE #219: Make liveness and readiness checks configurable
### Is your feature request related to a problem?

Yes. We're running into the issue described in this thread occasionally and unpredictably: https://www.mail-archive.com/users@nifi.apache.org/msg14909.html

When this happens, the only fix is to restart the NiFi pods. Restarting Zookeeper has no effect. This can be detected by querying the NiFi REST API, so we can work around this by tweaking the liveness check. However, it's not currently configurable, so i'm requesting that it be made configurable while keeping the current configuration as the default.

### Describe the solution you'd like to see

Make the readiness and liveness checks configurable and expose the configuration in `NifiCluster.Spec.PodPolicy`.

### Describe alternatives you've considered

Writing an external `CronJob`, but that's just a bandaid for an appropriate solution until the problem is resolved in NiFi itself.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mh013370**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #219
| License         | Apache 2.0

### What's in this PR?

This makes the NiFi `Pod` readiness and liveness checks configurable. These are new optional fields, so if they aren't overridden, then the current defaults are still used as before. 

I've added this to both `v1` and `v1alpha1` API versions.

### Why?

See #219 for details.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [x] Append changelog with changes

### CODE REVIEW

**Comment by juldrixx** [comment]
The documentation must reflect this change.

**Review by juldrixx — COMMENTED** [review]
If I'm not mistaken, correct me @erdrix if I'm wrong, but you should not update the v1alpha1 CRD, only the v1. We do not update v1alpha1 anymore for resource in v1.

**Comment by michael81877** [comment]
> The documentation must reflect this change.

Good call! Will update the docs.

**Comment by juldrixx** [comment]
I confirmed it with @erdrix (a while ago, but forget 😂).

We know will work on v1 resources and won't update v1alpha1 anymore. It's how it works with resources in K8S.
And maybe we will, one day, move to a v2.

**Comment by mh013370** [comment]
> I confirmed it with @erdrix (a while ago, but forget 😂).
> 
> We will now work on v1 resources and won't update v1alpha1 anymore. It's how it works with resources in K8S. And maybe we will, one day, move to a v2.
> 
> Of course, for new resource or resource without v1 will still work on v1alpha1

Okay, i will remove the `v1alpha1` changes!

**Comment by mh013370** [comment]
I've removed the `v1alpha1` changes. This PR should be good to go!

**Comment by mh013370** [comment]
@juldrixx Do you see any more changes needed on this PR?

**Review by juldrixx — APPROVED** [review]

**Pull request merged**
